name: Update Media Files List

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate files.json
      run: |
        echo "[" > files.json
        find . -type f \( \
          -iname "*.mp4" -o \
          -iname "*.webm" -o \
          -iname "*.gif" -o \
          -iname "*.jpg" -o \
          -iname "*.png" -o \
          -iname "*.jpeg" -o \
          -iname "*.mp3" -o \
          -iname "*.ogg" -o \
          -iname "*.wav" -o \
          -iname "*.avi" -o \
          -iname "*.mov" -o \
          -iname "*.flac" -o \
          -iname "*.mpg" -o \
          -iname "*.mkv" \
        \) -not -path "*/.git/*" -not -path "*/node_modules/*" | while read -r file; do
          clean_path="${file#./}"
          if [[ "$clean_path" != .git/* ]] && [[ "$clean_path" != .github/* ]]; then
            echo "  {\"url\": \"$clean_path\"}," >> files.json
          fi
        done
        sed -i '$ s/,$//' files.json
        echo "]" >> files.json

    - name: Create temporary deployment directory
      run: |
        mkdir deploy
        cp -r * deploy/ || true
        cp files.json deploy/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true

    - name: Commit files.json to main branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add files.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update files.json [skip ci]"
        git push
