name: Generate files.json

on:
  push:
    paths:
      - "*.mp4"
      - "*.webm"
      - "*.mov"
      - "*.gif"
      - "*.png"
      - "*.jpg"
      - "*.jpeg"

jobs:
  update_files_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate files.json
        run: |
          # Start with an empty files.json
          echo '[]' > files.json

          # Find and process all supported media files
          echo "Looking for files..."
          find . -type f \( -name "*.mp4" -o -name "*.webm" -o -name "*.mov" -o -name "*.gif" -o -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) | sed 's|^./||' | while read file; do
            echo "Adding file: $file"
            jq ". + [{\"name\": \"$(basename "$file")\", \"url\": \"https://xekoyt.github.io/Memes/$file\"}]" files.json > tmp.json && mv tmp.json files.json
          done

          # Debugging: print out the current content of files.json
          echo "files.json content:"
          cat files.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are changes
          git status

          # If changes, commit and push
          git add files.json
          git commit -m "Update files.json with new media files" || echo "No changes to commit"
          git push
