name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**/*'  # Watch all file types in the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (Optional)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies (Optional)
      run: npm install  # Remove this step if you don't need Node.js

    - name: Generate files.json
      run: |
        echo "[" > files.json
        for file in $(find ./ -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.gif" -o -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" -o -iname "*.mp3" -o -iname "*.ogg" -o -iname "*.wav" -o -iname "*.avi" -o -iname "*.mov" -o -iname "*.flac" -o -iname "*.mpg" -o -iname "*.mkv" \)); do
          echo "{\"url\": \"$file\"}," >> files.json
        done
        # Remove the trailing comma and close the JSON array
        sed -i '$ s/,$//' files.json
        echo "]" >> files.json

    - name: Build the site (Optional)
      run: |
        echo "Building the site..."  # Replace with your site's build commands if necessary

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add files.json
        git commit -m "Update media list"
        git push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust this if your output files are in a different directory
